# Generated by Django 5.2 on 2025-05-03 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='profile/', verbose_name='foto de perfil')),
                ('bio', models.TextField(verbose_name='Discricao')),
                ('field', models.CharField(choices=[('TA', 'TECNICO EM ADMINISTRACAO'), ('TC', 'TECNICO EM COMERCIO'), ('TCE', 'TECNICO EM COMERCIO EXTERIOR'), ('TCB', 'TECNICO EM CONTABILIDADE'), ('TF', 'TECNICO EM FINANCAS'), ('TM', 'TECNICO EM MARKETING'), ('TL', 'TECNICO EM LOGISTICA'), ('TRH', 'TECNICO EM RECURSOS HUMANOS')], max_length=5)),
                ('slug', models.SlugField(default=None, verbose_name='nome na url')),
                ('token', models.CharField(blank=True, max_length=30, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
