# Generated by Django 5.2 on 2025-05-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(default=None, editable=False, verbose_name='nome na url'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True),
        ),
    ]
