# Generated by Django 4.2.11 on 2025-06-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='field',
            field=models.CharField(choices=[('TA', 'ADMINISTRACAO'), ('TC', 'COMERCIO'), ('TCE', 'COMERCIO EXTERIOR'), ('TCB', 'CONTABILIDADE'), ('TF', 'FINANCAS'), ('TM', 'MARKETING'), ('TL', 'LOGISTICA'), ('TRH', 'RECURSOS HUMANOS')], max_length=5),
        ),
    ]
