# Generated by Django 5.2 on 2025-05-03 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='lesson_doc/', verbose_name='Material de Apoio')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('time', models.TimeField(verbose_name='tempo do video')),
                ('video', models.FileField(upload_to='lesson_video/', verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.material')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.video')),
            ],
        ),
    ]
