# Generated by Django 5.2 on 2025-05-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Ordem da aula'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, unique=True),
        ),
    ]
