# Generated by Django 5.2 on 2025-05-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_module_lesson_order_alter_lesson_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(unique=True, verbose_name='Ordem da aula'),
        ),
    ]
