# Generated by Django 5.2 on 2025-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_lesson_modulo_module_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-05'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='time',
            field=models.TimeField(verbose_name='Duracao do video'),
        ),
    ]
