# Generated by Django 5.2 on 2025-05-03 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_module_date_published_alter_video_time'),
        ('teacher', '0002_alter_teacher_slug_alter_teacher_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='date_published',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cover', models.FileField(upload_to='course_cover/')),
                ('category', models.CharField(choices=[('FC', 'FINANCAS E CONTABILIDADE'), ('NI', 'NEGOCIOS INTERNACIONAIS'), ('AG', 'ADMINISTRACAO E GESTAO'), ('MV', 'MARKETING E VENDAS'), ('EMP', 'EMPREENDEDORISMO'), ('AD', 'ANALISE DE DADOS'), ('RH', 'RECURSOS HUMANOS')], max_length=5)),
                ('created_at', models.DateField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
