# Generated by Django 5.2 on 2025-05-09 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_chat_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='chat',
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
    ]
