# Generated by Django 5.2 on 2025-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_comment_chat_comment_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_commented',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
