# Generated by Django 5.2 on 2025-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_comment_date_commented'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
