# Generated by Django 5.2 on 2025-06-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=None, editable=False),
        ),
    ]
