# Generated by Django 4.2.11 on 2025-06-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('Wh', 'WhatsApp'), ('Fb', 'FaceBook'), ('LI', 'LinkedIn')], max_length=100, verbose_name='Redes Sociais')),
                ('link', models.URLField(unique=True, verbose_name='Link da rede social')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
