# Generated by Django 5.2 on 2025-05-02 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=9, verbose_name='tel(+244)')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('profile_image', models.ImageField(blank=True, upload_to='profile/', verbose_name='Foto de Perfil')),
                ('bio', models.TextField(blank=True, verbose_name='Descricao')),
                ('slug', models.SlugField(blank=True, default=None, verbose_name='nome na url')),
                ('token', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
