# Generated by Django 5.2 on 2025-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_certificate',
            field=models.CharField(default=1, max_length=100, verbose_name='Nome para o certificado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='slug',
            field=models.SlugField(blank=True, default=None, editable=False, verbose_name='nome na url'),
        ),
        migrations.AlterField(
            model_name='student',
            name='token',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
    ]
