# Generated by Django 5.2 on 2025-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_name_certificate_alter_student_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Descricao'),
        ),
    ]
