# Generated by Django 5.2 on 2025-05-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof', models.FileField(upload_to='payment_proof/', verbose_name='Comprovativo')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.enrollment')),
            ],
        ),
    ]
