# Generated by Django 5.2 on 2025-05-25 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_paymentproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.enrollment'),
        ),
    ]
