# Generated by Django 5.2 on 2025-05-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_paymentproof_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='proof',
            field=models.ImageField(upload_to='payment_proof/', verbose_name='Comprovativo'),
        ),
    ]
