# Generated by Django 5.2 on 2025-05-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_paymentproof_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='proof',
            field=models.FileField(upload_to='payment_proof/', verbose_name='Comprovativo'),
        ),
    ]
